apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-data-integrity-demonstrator
  namespace: argocd
spec:
  destinations:
    - namespace: product-data-integrity-demonstrator
      server: https://kubernetes.default.svc
    - namespace: product-data-integrity-demonstrator-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-data-integrity-demonstrator.
      policies:
        - p, proj:project-data-integrity-demonstrator:team-admin, applications, *, project-data-integrity-demonstrator/*, allow
        - p, proj:project-data-integrity-demonstrator:team-admin, exec, create, project-data-integrity-demonstrator/*, allow
      groups:
        - catenax-ng:product-data-integrity-demonstrator
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-data-integrity-demonstrator:read-only, applications, get, project-data-integrity-demonstrator/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
