apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-item-relationship-service-frontend
  namespace: argocd
spec:
  description: Project for team item-relationship-service-frontend
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-item-relationship-service-frontend
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-item-relationship-service-frontend:project-read-only, applications, get, project-item-relationship-service-frontend/*, allow
        - p, proj:project-item-relationship-service-frontend:team-admin, exec, create, project-item-relationship-service-frontend/*, allow
      groups:
        - catenax-ng:product-item-relationship-service-frontend
        - catenax-ng:release-management
        - catenax-ng:test-management
