apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-registry-twin-check
  namespace: argocd
spec:
  destinations:
    - namespace: product-registry-twin-check
      server: https://kubernetes.default.svc
    - namespace: product-registry-twin-check-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-registry-twin-check.
      policies:
        - p, proj:project-registry-twin-check:team-admin, applications, *, project-registry-twin-check/*, allow
        - p, proj:project-registry-twin-check:team-admin, exec, create, project-registry-twin-check/*, allow
      groups:
        - Cofinity-X:product-registry-twin-check
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-registry-twin-check:read-only, applications, get, project-registry-twin-check/*, allow
      groups:
        - Cofinity-X:release-management
        - Cofinity-X:test-management
