apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-bpdm
  namespace: argocd
spec:
  destinations:
    - namespace: product-bpdm
      server: https://kubernetes.default.svc
    - namespace: product-bpdm-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-bpdm.
      policies:
        - p, proj:product-bpdm:team-admin, applications, *, product-bpdm/*, allow
        - p, proj:product-bpdm:team-admin, exec, create, product-bpdm/*, allow
      groups:
        - catenax-ng:product-bpdm
