apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-essential-services
  namespace: argocd
spec:
  description: Project for team essential services
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-essential-services
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-essential-services:project-read-only, applications, get, project-essential-services/*, allow
        - p, proj:project-essential-services:team-admin, exec, create, project-essential-services/*, allow
      groups:
        - catenax-ng:product-essential-services
        - catenax-ng:release-management
        - catenax-ng:test-management
