apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-esc-backbone
  namespace: argocd
spec:
  destinations:
    - namespace: product-esc-backbone
      server: https://kubernetes.default.svc
    - namespace: product-esc-backbone-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-esc-backbone.
      policies:
        - p, proj:product-esc-backbone:team-admin, applications, *, product-esc-backbone/*, allow
        - p, proj:product-esc-backbone:team-admin, exec, create, product-esc-backbone/*, allow
      groups:
        - catenax-ng:product-esc-backbone
