apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-traceability-foss
  namespace: argocd
spec:
  description: Project for team traceability-foss
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-traceability-foss
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-traceability-foss:project-read-only, applications, get, project-traceability-foss/*, allow
        - p, proj:project-traceability-foss:project-read-only, exec, create, project-traceability-foss/*, allow
      groups:
        - Cofinity-X:Trace-X
        - Cofinity-X:release-management
        - Cofinity-X:test-management
