apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-innovation-radar
  namespace: argocd
spec:
  destinations:
    - namespace: product-innovation-radar
      server: https://kubernetes.default.svc
    - namespace: product-innovation-radar-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-innovation-radar.
      policies:
        - p, proj:project-innovation-radar:team-admin, applications, *, project-innovation-radar/*, allow
        - p, proj:project-innovation-radar:team-admin, exec, create, project-innovation-radar/*, allow
      groups:
        - catenax-ng:product-innovation-radar
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-innovation-radar:read-only, applications, get, project-innovation-radar/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
