apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-innovation-radar
  namespace: argocd
spec:
  destinations:
    - namespace: product-innovation-radar
      server: https://kubernetes.default.svc
    - namespace: product-innovation-radar-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-innovation-radar.
      policies:
        - p, proj:product-innovation-radar:team-admin, applications, *, product-innovation-radar/*, allow
        - p, proj:product-innovation-radar:team-admin, exec, create, product-innovation-radar/*, allow
      groups:
        - catenax-ng:product-innovation-radar
