apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-esc-backbone
  namespace: argocd
spec:
  description: Project for team ESC-Backbone
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-esc-backbone
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-esc-backbone:project-read-only, applications, get, project-esc-backbone/*, allow
        - p, proj:project-esc-backbone:team-admin, exec, create, project-esc-backbone/*, allow
      groups:
        - catenax-ng:product-esc-backbone
        - catenax-ng:release-management
        - catenax-ng:test-management
