apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  irs-teams-channel-url: <path:devsecops/data/apps/argocd/argocd-notifications-secret#irs-teams-channel-url>
