apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-traceability-foss
  namespace: argocd
spec:
  destinations:
    - namespace: product-traceability-foss
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-traceability-foss.
      policies:
        - p, proj:project-traceability-foss:team-admin, applications, *, project-traceability-foss/*, allow
        - p, proj:project-traceability-foss:team-admin, exec, create, project-traceability-foss/*, allow
      groups:
        - Cofinity-x:Trace-x
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-traceability-foss:read-only, applications, get, project-traceability-foss/*, allow
      groups:
        - Cofinity-x:release-management
        - Cofinity-x:test-management