apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-daps
  namespace: argocd
spec:
  destinations:
    - namespace: product-daps
      server: https://kubernetes.default.svc
    - namespace: product-daps-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-daps.
      policies:
        - p, proj:project-daps:team-admin, applications, *, project-daps/*, allow
        - p, proj:project-daps:team-admin, exec, create, project-daps/*, allow
      groups:
        - Cofinity-X:DAPS
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-daps:read-only, applications, get, project-daps/*, allow
      groups:
        - Cofinity-X:release-management
        - Cofinity-X:test-management
