apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCDAdmins
  - ../../argocd/argocdadmins/read-write

  # Product Onboarding
  - ../../argocd/product-bpdm/read-write
  - ../../argocd/product-data-format-transformer/read-write
  - ../../argocd/product-essential-services/read-write
  - ../../argocd/product-managed-identity-wallets/read-write
  - ../../argocd/product-portal/read-write
  - ../../argocd/product-semantics/read-write
  - ../../argocd/product-traceability-foss/read-write
  - ../../argocd/product-traceability-irs/read-write
