apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  avp.kubernetes.io/path: "devsecops/data/apps/argocd/argocd-notifications-secret"
stringData:
  irs-teams-channel-url: <irs-teams-channel-url>
