apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-traceability-irs
  namespace: argocd
spec:
  destinations:
    - namespace: product-traceability-irs
      server: https://kubernetes.default.svc
    - namespace: product-traceability-irs-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-traceability-irs.
      policies:
        - p, proj:product-traceability-irs:team-admin, applications, *, product-traceability-irs/*, allow
        - p, proj:product-traceability-irs:team-admin, exec, create, product-traceability-irs/*, allow
      groups:
        - catenax-ng:product-traceability-irs
