apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-test-data-generator
  namespace: argocd
spec:
  description: Project for team test-data-generator
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-test-data-generator
      server: https://kubernetes.default.svc
    - namespace: product-test-data-generator-pen
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-test-data-generator:project-read-only, applications, get, project-test-data-generator/*, allow
        - p, proj:project-test-data-generator:project-read-only, exec, create, project-test-data-generator/*, allow
      groups:
        - catenax-ng:product-test-data-generator
        - catenax-ng:release-management
        - catenax-ng:test-management
