apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-example
  namespace: argocd
spec:
  description: Project for team example
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-example
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-example:project-read-only, applications, get, project-example/*, allow
        - p, proj:project-example:project-read-only, exec, create, project-example/*, allow
      groups:
        - catenax-ng:product-team-example
        - catenax-ng:release-management
        - catenax-ng:test-management
