apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCDAdmins
  # - ../../argocd/argocdadmins/read-write

  # Product Onboarding
  - ../../argocd/product-example/read-write
