apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base-read-only

resources:
  - resources/avp-secret.yaml
  - resources/namespace.yaml

patchesStrategicMerge:
  - resources/argo-project.yaml
#  - resources/argocd-notifications-cm.yaml
#  - resources/argocd-notifications-secret.yaml
