apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-test-data-generator
  namespace: argocd
spec:
  destinations:
    - namespace: product-test-data-generator
      server: https://kubernetes.default.svc
    - namespace: product-test-data-generator-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-test-data-generator.
      policies:
        - p, proj:project-test-data-generator:team-admin, applications, *, project-test-data-generator/*, allow
        - p, proj:project-test-data-generator:team-admin, exec, create, project-test-data-generator/*, allow
      groups:
        - catenax-ng:product-test-data-generator
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-test-data-generator:read-only, applications, get, project-test-data-generator/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
