apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-test-data-generator
  namespace: argocd
spec:
  destinations:
    - namespace: product-test-data-generator
      server: https://kubernetes.default.svc
    - namespace: product-test-data-generator-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-test-data-generator.
      policies:
        - p, proj:product-test-data-generator:team-admin, applications, *, product-test-data-generator/*, allow
        - p, proj:product-test-data-generator:team-admin, exec, create, product-test-data-generator/*, allow
      groups:
        - catenax-ng:product-test-data-generator
