apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-traceability-irs
  namespace: argocd
spec:
  description: Project for team traceability-irs
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-traceability-irs
      server: https://kubernetes.default.svc
    - namespace: product-traceability-irs-pen
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-traceability-irs:project-read-only, applications, get, project-traceability-irs/*, allow
        - p, proj:project-traceability-irs:project-read-only, exec, create, project-traceability-irs/*, allow
      groups:
        - catenax-ng:product-traceability-irs
        - catenax-ng:release-management
        - catenax-ng:test-management
