apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base-read-only

#Not needed for interim set up
#resources: 
#  - resources/avp-secret.yaml
#  - resources/namespace.yaml

patchesStrategicMerge:
  - resources/argo-project.yaml
