apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-innovation-radar
  namespace: argocd
spec:
  description: Project for team Innovation Radar
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-innovation-radar
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-innovation-radar:project-read-only, applications, get, project-innovation-radar/*, allow
        - p, proj:project-innovation-radar:project-read-only, exec, create, project-innovation-radar/*, allow
      groups:
        - catenax-ng:product-innovation-radar
        - catenax-ng:release-management
        - catenax-ng:test-management
