apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-item-relationship-service-frontend
  namespace: argocd
spec:
  destinations:
    - namespace: product-item-relationship-service-frontend
      server: https://kubernetes.default.svc
    - namespace: product-item-relationship-service-frontend-pen
      server: https://kubernetes.default.svc
  roles:
    - name: team-admin
      description: All access to applications inside project-item-relationship-service-frontend.
      policies:
        - p, proj:product-item-relationship-service-frontend:team-admin, applications, *, product-item-relationship-service-frontend/*, allow
        - p, proj:product-item-relationship-service-frontend:team-admin, exec, create, product-item-relationship-service-frontend/*, allow
      groups:
        - catenax-ng:product-item-relationship-service-frontend
