apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-explorer
  namespace: argocd
spec:
  description: Project for team explorer
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-explorer
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-explorer:project-read-only, applications, get, project-explorer/*, allow
        - p, proj:project-explorer:team-admin, exec, create, project-explorer/*, allow
      groups:
        - catenax-ng:product-explorer
        - catenax-ng:release-management
        - catenax-ng:test-management
