apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - resources/argo-project.yaml
#  - resources/argo-repo.yaml #This is not needed for the public repos
  - resources/avp-secret.yaml
  - resources/namespace.yaml
